"""Repository port for session persistence (B1)."""
from __future__ import annotations

from abc import ABC, abstractmethod
from datetime import datetime
from typing import Any, Optional

from app.domain.entities.session import Session, SessionMode


class SessionsRepository(ABC):
    """Abstract sessions store. Implementations: SQLite (current), Postgres (future)."""

    @abstractmethod
    def create(
        self,
        *,
        session_id: str,
        user_id: str,
        scenario: str,
        my_language: str,
        other_language: str,
        is_recording: bool,
        title: Optional[str],
        metadata: Optional[dict[str, Any]] = None,
        mode: SessionMode = "agent",
        meeting_id: Optional[str] = None,
    ) -> Session:
        """Create a new session row. ``session_id`` is generated by the use case (UUID4).

        ``mode`` picks between ``agent`` (1st-person responses) and
        ``scribe`` (3rd-person structured notes). Defaults to ``"agent"``
        so legacy callers keep their existing behaviour.

        ``meeting_id`` optionally links the session to a provider-agnostic
        Meeting row (Sprint 1.5). Defaults to ``None`` — callers without an
        associated meeting keep the historical behaviour."""
        ...

    @abstractmethod
    def get(self, session_id: str, user_id: str) -> Optional[Session]:
        """Fetch a session by id, scoped to user. Excludes soft-deleted rows."""
        ...

    @abstractmethod
    def get_including_deleted(
        self, session_id: str, user_id: str
    ) -> Optional[Session]:
        """Fetch a session by id, scoped to user, INCLUDING soft-deleted rows.

        Used by idempotent/lifecycle endpoints that need to distinguish
        between 404 (truly absent) and 410 Gone (soft-deleted)."""
        ...

    @abstractmethod
    def get_active_for_user(self, user_id: str) -> Optional[Session]:
        """Return most recent un-ended, non-deleted session (FR-22 recovery)."""
        ...

    @abstractmethod
    def list(
        self,
        *,
        user_id: str,
        scenario: Optional[str] = None,
        search: Optional[str] = None,
        limit: int = 20,
        offset: int = 0,
    ) -> list[Session]:
        """List user's sessions. Excludes soft-deleted rows."""
        ...

    @abstractmethod
    def update(
        self,
        *,
        session_id: str,
        user_id: str,
        title: Optional[str] = None,
        ended_at: Optional[datetime] = None,
        duration_seconds: Optional[int] = None,
        summary: Optional[str] = None,
        action_items: Optional[list[str]] = None,
        metadata: Optional[dict[str, Any]] = None,
    ) -> Session:
        """Patch a session. None fields are left untouched."""
        ...

    @abstractmethod
    def soft_delete(self, session_id: str, user_id: str) -> bool:
        """Set ``deleted_at`` (does not DELETE the row). Returns True if a row was affected."""
        ...

    @abstractmethod
    def count_for_user(self, user_id: str) -> int:
        """Total non-deleted sessions for a user."""
        ...

    @abstractmethod
    def list_stale_active(
        self, *, started_before: datetime
    ) -> list[Session]:
        """Return active (un-ended), non-deleted sessions whose
        ``started_at`` is strictly older than ``started_before``.

        Used by the ``cleanup_abandoned_sessions`` cron to find sessions
        that may have been created (via the modal) but never received
        any audio/transcripts. NOT scoped by user — the cron iterates
        globally.
        """
        ...

    @abstractmethod
    def mark_abandoned(self, session_id: str) -> bool:
        """Close a session that never received any transcripts.

        Sets ``ended_at = started_at`` and ``duration_seconds = 0`` so
        the session is no longer active (FR-22 recovery skips it) and
        downstream summary tasks treat it as a zero-length session.

        Returns True when a row was updated, False otherwise (already
        ended, soft-deleted, or unknown id).
        """
        ...
