"""Session domain entity (B1).

A live capture session: one row created on session start, ``ended_at`` set
on session end. Multi-tenant via ``user_id``. Pure data — no framework
or infrastructure dependencies."""
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Literal, Optional


SessionStatus = Literal["active", "ended", "abandoned"]
SessionMode = Literal["agent", "scribe"]
"""Session mode — orthogonal to scenario.

- ``agent`` (default): Susurra responds in the user's voice (1st-person).
- ``scribe``: Susurra observes silently and produces structured notes
  (3rd-person).

The scenario picks the DOMAIN (legal / interview / business / etc), the mode
picks the BEHAVIOUR. Same ``legal_client_call`` scenario can run agent OR
scribe — the prompt builder branches on ``mode`` to swap the system prompt
template while keeping the scenario context (identity docs, scenario docs,
reference docs, screen text, session materials)."""


@dataclass
class Session:
    """A live conversation session.

    ``id`` is a UUID4 (string) — generated by the use case, not the DB.
    ``status`` is a derived property; the DB stores presence/absence of
    ``ended_at`` + ``deleted_at`` instead of a status enum to keep writes
    cheap and avoid drift between two sources of truth."""

    id: str
    user_id: str
    scenario: str
    title: Optional[str]
    my_language: str
    other_language: str
    started_at: datetime
    ended_at: Optional[datetime]
    duration_seconds: Optional[int]
    is_recording: bool
    summary: Optional[str]
    action_items: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    deleted_at: Optional[datetime] = None
    mode: SessionMode = "agent"
    """Session mode — defaults to ``"agent"`` for backward-compat with rows
    created before scribe mode existed and for code paths that don't supply
    a mode (most tests, legacy callers). The DB migration also defaults
    existing rows to ``'agent'``."""
    meeting_id: Optional[str] = None
    """Optional FK to ``meetings.id``. Sprint 1.5 wires the session ↔
    meeting association so /app/live can surface the join URL alongside
    the live controls. Nullable: sessions without an associated Meet
    invite (the default) keep ``None`` and the UI hides the meeting card."""

    @property
    def status(self) -> SessionStatus:
        if self.deleted_at is not None:
            return "ended"
        if self.ended_at is not None:
            return "ended"
        # Heuristic for stale rows; consumers can promote 'active' -> 'abandoned'
        # if started_at is too far in the past. Kept as a property so it stays
        # authoritative without requiring a column.
        return "active"
